# Generated by Django 4.2.3 on 2023-07-23 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="type",
            new_name="user_type",
        ),
    ]
