# Generated by Django 4.2.3 on 2023-07-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_rename_type_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
