# Generated by Django 4.2.3 on 2023-07-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="container_attachment",
            name="container",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="container.container",
            ),
            preserve_default=False,
        ),
    ]
