# Generated by Django 4.2.3 on 2023-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0002_container_attachment_container"),
    ]

    operations = [
        migrations.AddField(
            model_name="container_attachment",
            name="attachment_name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="container_attachment",
            name="attachment_path",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="container_attachment",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="container_attachment",
            name="modified_datetime",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
