# Generated by Django 4.2.3 on 2023-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0004_remove_container_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container_attachment",
            name="attachment_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="container_attachment",
            name="attachment_path",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="container_attachment",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="container_attachment",
            name="modified_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
