# Generated by Django 4.2.3 on 2023-07-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0005_alter_container_attachment_attachment_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="container_no",
            field=models.IntegerField(unique=True),
        ),
    ]
