# Generated by Django 4.2.3 on 2023-07-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0006_alter_container_container_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="container_no",
            field=models.IntegerField(),
        ),
    ]
