# Generated by Django 4.2.3 on 2023-07-27 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0013_rename_city_id_yard_city"),
        ("container", "0007_alter_container_container_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="container_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containers",
                to="meta.container_type",
            ),
        ),
    ]
