# Generated by Django 4.2.3 on 2023-07-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0010_alter_container_container_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container_attachment",
            name="attachment_path",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to="conatiner/%y/%m/%d"
            ),
        ),
    ]
