# Generated by Django 4.2.3 on 2023-07-29 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0012_alter_container_attachment_container"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container_attachment",
            name="attachment_path",
        ),
    ]
