# Generated by Django 4.2.3 on 2023-07-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0013_remove_container_attachment_attachment_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="container_attachment",
            name="attachment_path",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to="conatiner/%y/%m/%d"
            ),
        ),
    ]
