# Generated by Django 4.2.3 on 2023-07-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0013_rename_city_id_yard_city"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="active_state",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="meta.city"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="gst",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="hourly_rate",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="modified_datetime",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="owner_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="postal_code",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="meta.province",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="pst",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="repair_list_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="meta.container_type",
            ),
        ),
    ]
