# Generated by Django 4.2.3 on 2023-07-25 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_customer_active_state_customer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="modified_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
