# Generated by Django 4.2.3 on 2023-07-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0005_alter_customer_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
