# Generated by Django 4.2.3 on 2023-07-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0008_alter_customer_email_alter_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="active_state",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="customer",
            name="billing_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gst",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="hourly_rate",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="owner_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postal_code",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="pst",
            field=models.IntegerField(),
        ),
    ]
