# Generated by Django 4.2.3 on 2023-07-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customer",
            "0009_alter_customer_active_state_alter_customer_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="modified_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
