# Generated by Django 4.2.3 on 2023-07-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0013_rename_city_id_yard_city"),
        ("customer", "0016_alter_customer_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cities",
                to="meta.city",
            ),
        ),
    ]
