# Generated by Django 4.2.3 on 2023-07-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0002_city_province"),
    ]

    operations = [
        migrations.CreateModel(
            name="Container_Height",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Container_Length",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Container_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Container_Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
            ],
        ),
    ]
