# Generated by Django 4.2.3 on 2023-07-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0006_damage_area_repair_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
