# Generated by Django 4.2.3 on 2023-07-24 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0008_yard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yard",
            old_name="City",
            new_name="city",
        ),
    ]
