# Generated by Django 4.2.3 on 2023-07-24 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0009_rename_city_yard_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yard",
            name="created_datetime",
        ),
        migrations.RemoveField(
            model_name="yard",
            name="modified_datetime",
        ),
    ]
