# Generated by Django 4.2.3 on 2023-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0010_remove_yard_created_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yard",
            name="phone",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
