# Generated by Django 4.2.3 on 2023-07-24 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0011_alter_yard_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yard",
            old_name="city",
            new_name="city_id",
        ),
    ]
