# Generated by Django 4.2.3 on 2023-07-24 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0012_rename_city_yard_city_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yard",
            old_name="city_id",
            new_name="city",
        ),
    ]
