# Generated by Django 4.2.3 on 2023-07-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0013_rename_city_id_yard_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Dam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dam", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Rep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rep", models.CharField(max_length=30)),
            ],
        ),
    ]
