# Generated by Django 4.2.3 on 2023-07-24 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("container", "0003_container_attachment_attachment_name_and_more"),
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity_ledger",
            name="activity_type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="activity_ledger",
            name="container",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="container.container",
            ),
        ),
        migrations.AddField(
            model_name="activity_ledger",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="activity_ledger",
            name="modified_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="activity_ledger",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="activity_ledger",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
