# Generated by Django 4.2.3 on 2023-07-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0002_activity_ledger_activity_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity_timeline",
            name="activity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="activity.activity_ledger",
            ),
        ),
        migrations.AddField(
            model_name="activity_timeline",
            name="activity_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activity_timeline",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity_timeline",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="activity_timeline",
            name="modified_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="activity_timeline",
            name="status",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
