# Generated by Django 4.2.3 on 2023-07-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0003_activity_timeline_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity_inspection_attachment",
            name="activity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="activity.activity_ledger",
            ),
        ),
        migrations.AddField(
            model_name="activity_inspection_attachment",
            name="attachment_path",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="activity_inspection_attachment",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="activity_inspection_attachment",
            name="modified_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
