# Generated by Django 4.2.3 on 2023-07-24 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("container", "0003_container_attachment_attachment_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activity", "0005_activity_comment_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity_log",
            name="container",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="container.container",
            ),
        ),
        migrations.AddField(
            model_name="activity_log",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="activity_log",
            name="current_state",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activity_log",
            name="log_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activity_log",
            name="log_type_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="activity.activity_ledger",
            ),
        ),
        migrations.AddField(
            model_name="activity_log",
            name="target_state",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activity_log",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
