# Generated by Django 4.2.3 on 2023-07-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
        (
            "activity",
            "0008_activity_quote_repair_attachment_activity_quote_repair_list_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activity_invoice",
            name="activity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="activity.activity_ledger",
            ),
        ),
        migrations.AddField(
            model_name="activity_invoice",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoice.invoice",
            ),
        ),
    ]
