# Generated by Django 4.2.3 on 2023-07-25 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "activity",
            "0010_rename_attachment_path_activity_quote_repair_attachment_damaged_area_attachment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity_comment",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="activity_quote_repair_list",
            name="comment",
        ),
        migrations.AddField(
            model_name="activity_comment",
            name="comment_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="activity.activity_quote_repair_list",
            ),
        ),
    ]
