# Generated by Django 4.2.3 on 2023-08-02 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0012_comment_delete_activity_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity_ledger",
            name="created_datetime",
        ),
        migrations.AddField(
            model_name="activity_ledger",
            name="activity_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 8, 2, 3, 15, 3, 996636, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
