# Generated by Django 4.2.3 on 2023-08-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0014_alter_activity_ledger_activity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity_ledger",
            name="status",
            field=models.CharField(default="idle", max_length=50),
        ),
    ]
