# Generated by Django 4.2.3 on 2023-08-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "activity",
            "0024_rename_activity_quote_repair_list_activity_quote_repair_attachment_act_quote_repair_list",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity_timeline",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="activity.activity_ledger",
            ),
        ),
        migrations.AlterField(
            model_name="activity_timeline",
            name="activity_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="activity_timeline",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="activity_timeline",
            name="status",
            field=models.CharField(max_length=100),
        ),
    ]
