# Generated by Django 4.2.3 on 2023-08-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0026_activity_timeline_status_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity_timeline",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_timeline",
                to="activity.activity_ledger",
            ),
        ),
    ]
